### ISSUE TITLE
how to reproduce input tensor

### ISSUE THREAD

**Issue by gkazunii** [dgchachlakis/The-exact-solution-to-rank-1-L1-norm-Tucker2-decomposition#2]
Thank you for your uploading code !!
It helps a lot.

I would like to use your algorithm to reproduce input tensor by rank-1 tensor.
In this case, do I have to do like below?

```
T1 = np.empty((D,M,N))
for n in range(N):
    T1[:,:,n] = np.tensordot(uopt_exactpoly, uopt_exactpoly, axes=0) @ tensor[:,:,n] @ np.tensordot(vopt_exactpoly, vopt_exactpoly, axes=0)
```

Is it correct?

**Comment by dgchachlakis** [comment]
You are very welcome. I am glad the code helps. 

Regarding your question, the code appears correct. Alternatively, you can also use the following code:

```python
T1 = np.empty((D, M, N)) 
for n in range(N):
    T1[:, :, n] = np.outer(uopt_exactpoly, uopt_exactpoly) @ tensor[:, :, n] @ np.outer(vopt_exactpoly, vopt_exactpoly)
```

After your code of block (or, the above alternative) is executed, then every matrix measurement across mode-3 of the tensor will have been rank-1 approximated.
